---

- hosts: tag_Name_gm_control_api_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-acert
    - ansible-role-control-api
    - ansible-role-gmcli
    - ansible-role-jsons

- hosts: tag_Name_gm_control_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-control

- hosts: tag_Name_gm_proxy_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-proxy

- hosts: tag_Name_gm_data_ubuntu
  user: ubuntu
  become: yes
  roles:
    - ansible-role-preparatory
    - ansible-role-incert
    - ansible-role-mongodb
    - ansible-role-redis
    - ansible-role-certs
    - ansible-role-internaljwt
    - ansible-role-data
    - ansible-role-acert
  vars:
    acert_service: gm-data