---

- hosts: localhost
  connection: local
  tasks:
  - import_role:
      name: ecs_services_fargate
    vars:
      aws_region: 'us-east-1'
      cluster_name: 'greymatter-ecs-cluster'
      credentials_parameter: 'arn:aws:secretsmanager:us-east-1:706634194319:secret:ecs-greymatter-ci-emFEzR'
      ecs_instance_role: 'arn:aws:iam::706634194319:role/ecsInstanceRole'
      elb_control: 'internal-greymatter-ecs-alb-control-445335798.us-east-1.elb.amazonaws.com'
      elb_control_api: 'internal-greymatter-ecs-alb-control-api-2029981198.us-east-1.elb.amazonaws.com'
      greymatter_proxy_image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.8.1'
      security_group: 'sg-058ff37fcba82d64e'
      subnet_list: 'subnet-0e06fb4f956d9f5f8,subnet-0e06fb4f956d9f5f8,subnet-0e06fb4f956d9f5f8'
      task_target_group_control: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-ip-control/e27b15d6c8ba30a9'
      task_target_group_control_api: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-ip-control-api/3c56697acb1a76ea'
      task_target_group_edge: 'arn:aws:elasticloadbalancing:us-east-1:706634194319:targetgroup/gm-ecs-alb-tg-ip-edge/086f4c99fd21c87e'
