---

  - name: IAM role for ec2 instances and services
    iam_role:
      name: ecsInstanceRole
      assume_role_policy_document: "{{ lookup('file', 'ec2-trust-policy.json'}}"
      state: present
      create_instance_profile: yes
      managed_policy:
      - AmazonEC2ContainerServiceforEC2Role
