---

  - name: Create task definition edge
    ecs_taskdefinition:
      state: present
      network_mode: bridge
      family: "greymatter-edge"
      launch_type: EC2
      cpu: 512
      memory: 1024
      region: "{{ aws_region }}"
      execution_role_arn: "{{ ecs_instance_role }}"
      task_role_arn: "{{ ecs_instance_role }}"
      containers:
      - name: edge
        secrets:
        - name: INGRESS_TLS_CERT
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-cert-b64-GvrspG
        - name: INGRESS_TLS_KEY
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-key-b64-m46Nvr
        - name: EGRESS_TLS_CERT
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-server-b64-uIFYGU
        - name: EGRESS_TLS_KEY
          valueFrom: arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-server-key-b64-L0xcew
        - name: EGRESS_TLS_TRUST
          valueFrom:  arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-ca-oyDcNY
        - name: INGRESS_TLS_TRUST
          valueFrom:  arn:aws:secretsmanager:us-east-1:269783025111:secret:sidecar-certs-ca-oyDcNY
        essential: true
        image: "{{ greymatter_proxy_image }}"
        repositoryCredentials:
          credentialsParameter: "{{ credentials_parameter_proxy }}"
        dockerLabels:
           gm-cluster: "edge:7080"
        environment:
        - name: "PROXY_DYNAMIC"
          value: "true"
        - name: "ENVOY_ADMIN_LOG_PATH"
          value: "/dev/stdout"
        - name: "XDS_CLUSTER"
          value: edge
        - name: "XDS_HOST"
          value: "{{ control_ip }}"
        - name: "XDS_PORT"
          value: 50000
        - name: "XDS_NODE_ID"
          value: "default"
        - name: "METRICS_PORT"
          value: 7081
        - name: "PORT"
          value: 7080
        - name: "ENVOY_ADMIN_PORT"
          value: 7001
        portMappings:
        - containerPort: 7081
          hostPort: 7081
          protocol: tcp
        - containerPort: 7080
          hostPort: 7080
          protocol: tcp
        - containerPort: 7001
          hostPort: 7001
          protocol: tcp
        logConfiguration:
          logDriver: awslogs
          options:
            awslogs-group: openjobs
            awslogs-region: "{{ aws_region }}"
            awslogs-stream-prefix: web
    register: task_output
  
  - name: ECS service edge
    ecs_service:
      state: present
      name: edge
      cluster: "{{ cluster_name }}"
      region: "{{ aws_region }}"
      launch_type: EC2
      task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
      desired_count: 1
      load_balancers:
        - targetGroupArn: "{{ task_target_group_edge }}"
          containerName: edge
          containerPort: 7080
    register: "ecs_service"
